### ISSUE TITLE
Ignore tweet URLs that are in Markdown links

### ISSUE THREAD

**Issue by nhoizey** [takuti/jekyll-lazy-tweet-embedding#1]
I sometimes link to tweets without any intent to show the actual tweet in my page.

This plugin should IMHO just show tweet widgets on tweet URLs that are "alone" on one line.

**Comment by takuti** [comment]
Hi @nhoizey, thanks for the comment 👍  I definitely agree with your opinion that only the last url in the following markdown must be converted. 

``` markdown
I would like to add a link to [tweet](https://twitter.com/twitter/status/748610658405519360), or just put a url as https://twitter.com/twitter/status/748218099392929792.

https://twitter.com/twitter/status/747521153195876352

The above tweet url must be converted into a twitter card.
```

I have fixed the issue in 61d0a226b6786d5a7cca021f603d07e46c180702 by a tiny regex fix. Please try the latest version on your site.

**Comment by takuti** [comment]
BTW, thanks to your suggestion, I noticed another issue that multiple occurrences of the same URL in an article lead incorrect results. I have also fixed this issue, and the latest version is [HERE](https://github.com/takuti/jekyll-lazy-tweet-embedding/blob/master/lazy_tweet_embedding.rb). You can try this version if possible :)

**Comment by nhoizey** [comment]
Yes, it fixed my issue, great job!
