### ISSUE TITLE
What gem to add to _config.yml?

### ISSUE THREAD

**Issue by alexdwagner** [takuti/jekyll-lazy-tweet-embedding#3]
Tried to implement plugin via readme instructions but it's not working for me. Is there a ruby gem I need to add to _config.yml in the "gems:" block?

**Comment by skyem123** [comment]
Strange, for me, I just needed to put the `.rb` file into the `_plugins` folder.

**Comment by takuti** [comment]
Yo don't need to make any modifications to `_config.yml`. It should work the `.rb` file alone as @skyem123 said. (See _option 1_ in [the official page](https://jekyllrb.com/docs/plugins/).)

Are there any error messages when you launch a server?

Or, I'm concerned that Lazy Tweet Embedding conflicts the other plugins. Are you using any other plugins which overrides the original markdown converter methods?

**Comment by alexdwagner** [comment]
I'm new to opening issues on github, so please forgive me if I'm not providing enough info, or not following etiquette. Attached are three screenshots. I created my _plugins folder for _lazy-tweet-embedding_, so no other plugins. When I include a tweet in a post, it just shows the tweet's web address, and not the embedded tweet.

I'm pushing to a github pages blog from the command line, so i'm not sure how to test for errors(or how to launch a server to test - would that be something like '$ jekyll serve'?). 

Any help is appreciated!

<img width="1533" alt="screen shot 2016-10-26 at 4 57 05 pm" src="https://cloud.githubusercontent.com/assets/16179566/19745212/bc1bb712-9b9e-11e6-9e74-9fabd0cd928d.png">

<img width="1530" alt="screen shot 2016-10-26 at 5 09 00 pm" src="https://cloud.githubusercontent.com/assets/16179566/19745274/f355873a-9b9e-11e6-8b73-08b38e4dee2d.png">

<img width="1011" alt="screen shot 2016-10-26 at 5 07 16 pm" src="https://cloud.githubusercontent.com/assets/16179566/19745213/bc1dccc8-9b9e-11e6-9268-05cea1cc0fcb.png">

**Comment by takuti** [comment]
Thanks for providing more information, and I just realized the reason. Unfortunately, in case you are using GitHub Pages, plugins under the `_plugins` directory do not work as expected.

I previously did similar discussion at [HERE](https://github.com/takuti/jekyll-lazy-tweet-embedding/issues/2#issuecomment-230667582). GitHub Pages only support plugins configured at the `gems:` section in `_confing.yml`, and using the other plugins which are placed under `_plugins/` (including lazy-tweet-embedding) is not straightforward.

If you really want to use lazy-tweet-embedding on GH pages, you need to follow a little bit complicated procedure:
1. Put the `.rb` file under `_plugins/` (you already completed this step)
2. **Locally** generate `_site/` by `$ jekyll serve` on your machine
3. Push the static site contents to GitHub pages

**Comment by alexdwagner** [comment]
thank you, Takuti. after asking some colleagues, I came to the same conclusion but did not know if there was a workaround. thanks for the help!
