### ISSUE TITLE
Support other oEmbed providers

### ISSUE THREAD

**Issue by Crissov** [takuti/jekyll-lazy-tweet-embedding#4]
I'm new to Ruby, but the code looks as if it should be rather simple to add other [oEmbed ](http://oembed.com/) [providers](http://oembed.com/providers.json).

**Comment by takuti** [comment]
@Crissov Thank you for suggestion. Could you describe a little bit more detail of your proposal? Why do you think supporting other oEmbed providers is necessary for this plugin? Do you have any ideas how to implement it?

**Comment by Crissov** [comment]
It&rsquo;s certainly not &ldquo;necessary&rdquo;, given the name of the plugin, but as an author who has learned to embed tweets simply by providing their URLs in separate lines, I&rsquo;d wonder whether I could pull content from other providers as well and I wouldn&rsquo;t want to install a separate plugin for every single one of them.

The resource [`providers.json`](http://oembed.com/providers.json) &ndash; which is probably trustworthy, but not complete: a [`twitter.yml` was missing](https://github.com/iamcal/oembed/pull/221) from the [Github repository](https://github.com/iamcal/oembed/tree/master/providers) for instance &ndash; could be parsed directly (once or regularly) for its `endpoints -> schemes` entries which would then be used to populate the regular expression _`r`_ in [`convert(line)`](https://github.com/takuti/jekyll-lazy-tweet-embedding/blob/master/lazy_tweet_embedding.rb#L28). The corresponding `endpoints -> url` would then be used in [`get_html(id)`](https://github.com/takuti/jekyll-lazy-tweet-embedding/blob/master/lazy_tweet_embedding.rb#L8), which would need to switch from using an `id` parameter to [`url`](http://oembed.com/#section2.2) and hence needs to become either `get_html(endpoint_url, resource_url)` or `get_html(request_url)`.

**Comment by takuti** [comment]
@Crissov Okay, I totally agree with your opinion. However, I guess searching appropriate `schemes` for each of URLs in an article might be time-consuming; for the many providers, we need to sequentially check if URL matches to `schemes` in terms of regex.

IMO, your idea is worthy to create a new Jekyll plugin named `jekyll-oembed-converter`, rather than extending my twitter-specific plugin.
